/**
 * Collection of diverse user personas for demo purposes
 * Each persona is randomly selected when entering the login flow
 */

const personas = [
  {
    id: '1',
    name: 'Maria Rodriguez',
    email: 'maria.rodriguez@example.com',
    password: 'password123',
    hasPassword: true,
    role: 'Farm Manager',
    initials: 'MR',
    gender: 'female',
    farmName: 'Sunnydale Organics',
    location: 'California',
    farmAddress: '123 Farm Lane',
    city: 'Sacramento',
    postalCode: '95829',
    region: 'California',
    country: 'United States'
  },
  {
    id: '2',
    name: 'Li Wei Chen',
    email: 'liwei.chen@example.com',
    password: null,  // Magic link only user
    hasPassword: false,
    role: 'Agricultural Consultant',
    initials: 'LC',
    gender: 'male',
    farmName: 'Eastern Horizons Farm',
    location: 'Oregon',
    farmAddress: '456 Pacific Hwy',
    city: 'Portland',
    postalCode: '97217',
    region: 'Oregon',
    country: 'United States'
  },
  {
    id: '3',
    name: 'Jamal Washington',
    email: 'jamal.washington@example.com',
    password: 'farmlife2024',
    hasPassword: true,
    role: 'Farm Owner',
    initials: 'JW',
    gender: 'male',
    farmName: 'Washington Family Farms',
    location: 'Georgia',
    farmAddress: '789 Peachtree St',
    city: 'Atlanta',
    postalCode: '30303',
    region: 'Georgia',
    country: 'United States'
  },
  {
    id: '4',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    password: 'dairyfarm',
    hasPassword: true,
    role: 'Farm Manager',
    initials: 'SJ',
    gender: 'female',
    farmName: 'Johnson Dairy',
    location: 'Wisconsin',
    farmAddress: '321 Dairy Rd',
    city: 'Madison',
    postalCode: '53703',
    region: 'Wisconsin',
    country: 'United States'
  },
  {
    id: '5',
    name: 'Ahmed Al-Farsi',
    email: 'ahmed.alfarsi@example.com',
    password: null,  // Magic link only user
    hasPassword: false,
    role: 'Farm Tech Specialist',
    initials: 'AA',
    gender: 'male',
    farmName: 'Innovation Agriculture',
    location: 'Arizona',
    farmAddress: '654 Innovation Way',
    city: 'Phoenix',
    postalCode: '85001',
    region: 'Arizona',
    country: 'United States'
  },
  {
    id: '6',
    name: 'Priya Patel',
    email: 'priya.patel@example.com',
    password: 'research123',
    hasPassword: true,
    role: 'Agricultural Scientist',
    initials: 'PP',
    gender: 'female',
    farmName: 'Green Solutions Research',
    location: 'Illinois',
    farmAddress: '147 Research Blvd',
    city: 'Chicago',
    postalCode: '60616',
    region: 'Illinois',
    country: 'United States'
  },
  {
    id: '7',
    name: 'David Kim',
    email: 'david.kim@example.com',
    password: 'orchard2024',
    hasPassword: true,
    role: 'Farm Manager',
    initials: 'DK',
    gender: 'male',
    farmName: 'Kim Family Orchards',
    location: 'Washington',
    farmAddress: '258 Orchard Ave',
    city: 'Seattle',
    postalCode: '98109',
    region: 'Washington',
    country: 'United States'
  },
  {
    id: '8',
    name: 'Isabella Rossi',
    email: 'isabella.rossi@example.com',
    password: null,  // Magic link only user
    hasPassword: false,
    role: 'Organic Farm Owner',
    initials: 'IR',
    gender: 'female',
    farmName: 'Bella Terra Organics',
    location: 'California',
    farmAddress: '369 Bella Terra Rd',
    city: 'Napa',
    postalCode: '94558',
    region: 'California',
    country: 'United States'
  },
  {
    id: '9',
    name: 'Kwame Osei',
    email: 'kwame.osei@example.com',
    password: 'harvest2024',
    hasPassword: true,
    role: 'Agricultural Engineer',
    initials: 'KO',
    gender: 'male',
    farmName: 'Sustainable Harvest',
    location: 'Texas',
    farmAddress: '159 Harvest Loop',
    city: 'Austin',
    postalCode: '73301',
    region: 'Texas',
    country: 'United States'
  },
  {
    id: '10',
    name: 'Emma Thompson',
    email: 'emma.thompson@example.com',
    password: 'ranchlife',
    hasPassword: true,
    role: 'Livestock Specialist',
    initials: 'ET',
    gender: 'female',
    farmName: 'Thompson Ranch',
    location: 'Montana',
    farmAddress: '753 Ranch Trail',
    city: 'Billings',
    postalCode: '59101',
    region: 'Montana',
    country: 'United States'
  },
  {
    id: '11',
    name: 'Miguel Hernandez',
    email: 'miguel.hernandez@example.com',
    password: null,  // Magic link only user
    hasPassword: false,
    role: 'Farm Operations Manager',
    initials: 'MH',
    gender: 'male',
    farmName: 'Hernandez Family Farms',
    location: 'New Mexico',
    farmAddress: '852 Desert Farm Rd',
    city: 'Albuquerque',
    postalCode: '87101',
    region: 'New Mexico',
    country: 'United States'
  },
  {
    id: '12',
    name: 'Aisha Khan',
    email: 'aisha.khan@example.com',
    password: 'future2024',
    hasPassword: true,
    role: 'Agricultural Researcher',
    initials: 'AK',
    gender: 'female',
    farmName: 'Future Farming Institute',
    location: 'Michigan',
    farmAddress: '963 Future Farm Dr',
    city: 'Lansing',
    postalCode: '48910',
    region: 'Michigan',
    country: 'United States'
  }
];

export default personas;
